name: Create Release and Scan with VirusTotal

on:
  # This allows you to run the workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version (e.g., v1.0.0)"
        required: true
        default: "v1.0.0"

jobs:
  build-scan-release:
    runs-on: windows-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Build the Executable
        run: |
          pip install pyinstaller pypdf tkinterdnd2
          pyinstaller --onefile --windowed --name "PDF_Merger" --hidden-import=tkinterdnd2 --version-file "version_info.txt" pdf_merger.py
        # Using the standard command because the GitHub runner environment is clean

      - name: 3. Upload to VirusTotal and Get Report
        id: vt-scan # Give this step an ID so we can reference its output
        uses: virustotal/vt-cli-action@v2
        with:
          vt-api-key: ${{ secrets.VT_API_KEY }}
          vt-args: "scan file dist/PDF_Merger.exe"

      - name: 4. Create GitHub Release with Scan Report
        uses: softprops/action-gh-release@v2
        with:
          # Use the version you entered when running the workflow
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          # This is the body of the release notes
          body: |
            ## PDF Merger Release ${{ github.event.inputs.version }}

            This is an automated release. The executable has been scanned for viruses.

            **VirusTotal Security Report:**
            [View Scan Results](${{ steps.vt-scan.outputs.analysis_url }})

            *Please review the report before downloading.*
          # The files to attach to the release
          files: |
            dist/PDF_Merger.exe
